# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0007_auto_20171124_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='votantes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100, verbose_name='votos'),
        ),
    ]
